import { X } from 'lucide-react'
import { motion } from 'framer-motion'
import type { GeneratedDocument, PaymentDetails } from '../types'

interface QuoteOverlayProps {
  doc: GeneratedDocument
  payment: PaymentDetails
  onClose: () => void
  onShare: () => void
  onSave?: () => void
  showSave: boolean
}

export function QuoteOverlay({
  doc,
  payment,
  onClose,
  onShare,
  onSave,
  showSave,
}: QuoteOverlayProps) {
  const title = doc.type === 'quote' ? 'Quote' : 'Invoice'

  return (
    <motion.div
      initial={{ y: '100%' }}
      animate={{ y: 0 }}
      className="fixed inset-0 z-[90] flex flex-col bg-white text-black"
    >
      <div className="flex items-center justify-between border-b border-black/10 px-4 py-3">
        <span className="font-display text-sm text-black/50">{title}</span>
        <button type="button" onClick={onClose} className="min-h-[48px] min-w-[48px]">
          <X size={22} className="text-black" />
        </button>
      </div>
      <div className="flex-1 overflow-y-auto px-4 pb-32 pt-4">
        <div className="flex justify-between gap-4">
          {payment.logo ? (
            <img src={payment.logo} alt="Logo" className="h-12 w-auto object-contain" />
          ) : (
            <span className="font-display text-lg font-bold">Bangon</span>
          )}
          <div className="text-right font-body text-xs">
            {payment.businessName && <p className="font-medium">{payment.businessName}</p>}
            {payment.abn && <p>ABN {payment.abn}</p>}
          </div>
        </div>
        <hr className="my-4 border-black/10" />
        <h1 className="font-display text-2xl font-bold">{title}</h1>
        <p className="mt-2 font-body text-sm">#{doc.number} · {doc.date}</p>
        {doc.clientName && (
          <p className="mt-4 font-body text-sm">
            <span className="font-medium">Client:</span> {doc.clientName}
            {doc.clientAddress && ` · ${doc.clientAddress}`}
          </p>
        )}
        {doc.dueDate && (
          <p className="mt-1 font-body text-sm">
            <span className="font-medium">Due:</span> {doc.dueDate}
          </p>
        )}
        <table className="mt-6 w-full font-body text-sm">
          <thead>
            <tr className="border-b border-black/20 text-left text-xs text-black/60">
              <th className="pb-2">Description</th>
              <th className="pb-2 text-right">Qty</th>
              <th className="pb-2 text-right">Price</th>
              <th className="pb-2 text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            {doc.lineItems.map((item, i) => (
              <tr key={i} className="border-b border-black/5">
                <td className="py-2 pr-2">{item.description}</td>
                <td className="py-2 text-right">{item.quantity}</td>
                <td className="py-2 text-right">${item.unitPrice.toFixed(2)}</td>
                <td className="py-2 text-right">${item.total.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="mt-4 space-y-1 font-body text-sm text-right">
          <p>Subtotal: ${doc.subtotal.toFixed(2)}</p>
          {doc.includeGst && <p>GST: ${doc.gst.toFixed(2)}</p>}
          <p className="font-display text-lg font-bold">Total: ${doc.total.toFixed(2)}</p>
        </div>
        {doc.type === 'invoice' && payment.bsb && (
          <p className="mt-6 font-body text-xs text-black/60">
            Pay to BSB {payment.bsb} · Acc {payment.account}
          </p>
        )}
        <p className="mt-8 font-body text-xs text-black/40">Generated by Bangon</p>
      </div>
      <div className="fixed bottom-0 left-0 right-0 flex gap-2 border-t border-black/10 bg-white p-4">
        <button
          type="button"
          onClick={onShare}
          className="min-h-[48px] flex-1 rounded-xl border border-black/20 font-body text-sm"
        >
          Share with client
        </button>
        {showSave && onSave ? (
          <button
            type="button"
            onClick={onSave}
            className="min-h-[48px] flex-1 rounded-xl bg-black font-body text-sm text-white"
          >
            Save to job
          </button>
        ) : (
          <button
            type="button"
            onClick={onClose}
            className="min-h-[48px] flex-1 rounded-xl bg-black font-body text-sm text-white"
          >
            Done
          </button>
        )}
      </div>
    </motion.div>
  )
}
